# Generated by Django 4.1.1 on 2022-09-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="password",
            field=models.CharField(max_length=200, verbose_name="비밀번호"),
        ),
    ]
